/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Background(props) {
  const { nodes, materials } = useGLTF('/models/background.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0, 29, 0]}
        scale={[30, 40, 30]}
      >
        <meshStandardMaterial color="#32aaa6" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/background.glb')