/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Emmision(props) {
  const { nodes, materials } = useGLTF('/models/emission.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0, 2, -2]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.5]}
      >
      <meshStandardMaterial emissive="#87fffb" emissiveIntensity={30} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/emission.glb')