/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { DoubleSide } from 'three'

export function Heart(props) {
  const { nodes, materials } = useGLTF('/models/heart.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.heart.geometry}
        material={nodes.heart.material}
      >
        <meshStandardMaterial color={"#87fffb"} roughness={0} side={DoubleSide}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/heart.glb')
